### ISSUE TITLE
Unsupported file given on commandline

### ISSUE THREAD

**Issue by SethWiiPlaza** [UInt2048/CyberKit#1]
_Specs:_
**iPhone 11
iOS 14.0.1 
unc0ver 8.0.2**

<details>
<summary>Photo with error installing in Zebra</summary>

![image](https://user-images.githubusercontent.com/8001327/233901694-c5fac0bc-5e3a-4ac8-8eae-d8001a20c134.jpeg)
</details>

**Comment by UInt2048** [comment]
I've updated all my DEB files. Does installing the latest version work now?

**Comment by UInt2048** [comment]
@SethWiiPlaza Please let me know if this occurs again.
