### ISSUE TITLE
CyberKit 0.0.8-alpha is unable to use the iOS file picker

### ISSUE THREAD

**Issue by SprintKeyz** [UInt2048/CyberKit#19]
Every time I attempt to pick a file it crashes. Is there a way around it? I’m using CyberKit Fennec 0.0.8-alpha for iOS 14.

**Comment by UInt2048** [comment]
I've created a nightly release of MobileMiniBrowser for you to confirm the fix.

**Comment by Ectalite** [comment]
MobileMiniBrowser works as intended when using the file picker on iOS 14 for me.
