### ISSUE TITLE
Fennec is very slow on iPhone 7 iOS 13.4.1

### ISSUE THREAD

**Issue by driftyz700** [UInt2048/CyberKit#20]
Using an iOS 13.4.1 iPhone 7 128gb variant, CyberKit 0.0.8 fennec doesn't load any website other than plain google.com and even that takes like 5-10 minutes to load (Jetsam and plistbuddy are installed and properly) Reverting jetsam to vanilla safari/webkit for now because this is not usable. The phone is checkra1n jb and works alright system-wise its not that slow in any possible situation thus why I suspect its just the newer webkit

**Comment by UInt2048** [comment]
Duplicate of #12
