### ISSUE TITLE
New automatic jetsam configuration doesn't work

### ISSUE THREAD

**Issue by mike-code** [UInt2048/CyberKit#21]
my setup: ios 14.5.1 w/ unc0ver and substitute. jetsam set to "lienient" in substitute and [SamJet](https://www.reddit.com/r/jailbreak/comments/skyxoi/free_release_samjet_a_more_stable_ios_14/) pkg installed

Ive tried both ipa installation through filza or trollstore and deb via dpkg, but the results are the same. Ie, I open minibrowser app, I can see some website is trying to load but it instantly goes blank (whitepage). If I enter an address in the bar and hit Go, Ill promptly see that https was prepended to the domain, the viewport will "blink", and then itll turn white as well as the address bar will be erased

btw, the new version of webkit would only work in the demo app or is it possible to make it system-wide, ie the apps that use in-app browser would also benefit from updated webkit version?

**Comment by UInt2048** [comment]
The above issue was reported with v0.0.8 nightly 6, but a new release has been published.

The official report of this issue using v0.0.8 nightly 7 will proceed as follows:

**Expected behavior:** This nightly release of CyberKit should work normally, just as v0.0.8 alpha did.

**Actual behavior:**

1. The first launch of MobileMiniBrowser soft fails, appearing as a never-ending page load with 100% on the progress bar.
2. If MobileMiniBrowser is closed and reopened, https://webkit.org does successfully load. Browsing webkit.org does work, but other sites do not seem to work.
3. The third and fourth launch will instantly go blank as reported above.
4. The fifth launch will work to view webkit.org as did the second, and so on.

**Comment by deepfriedfilth** [comment]
I've tried v0.0.8 nightly 7 and having the same results as @mike-code on an iPhone 7 running checkra1n on iOS 14.4 without editing jetsam manually.

**Comment by UInt2048** [comment]
@deepfriedfilth I know it sounds silly, but is the behavior affected if you uninstall it and reinstall it?

**Comment by deepfriedfilth** [comment]
@UInt2048 After removing the .deb and installing again, websites still don't load. Just tried a dozen times. Although, instead of the progress bar "freezing" at the aforementioned length, now both it and the URL disappear, which is more consistent with OP's issue.

**Comment by mike-code** [comment]
after installing nightly 7, the progress bar goes to around 60%, then freezes. The website wont load although the URL doesnt disappear from the address bar.

**Comment by UInt2048** [comment]
@mike-code @deepfriedfilth

Please confirm the issue is no longer present in v0.0.8 nightly 8.

**Comment by UInt2048** [comment]
> is a user space reboot still required with the new baked-in automagic jetsam config?

Legacy jetsam configuration required a full reboot; a userspace reboot was not sufficient.

Today, automatic jetsam configuration requires no reboot of any kind.

**Comment by deepfriedfilth** [comment]
Hmm.. I'm still experiencing the same issue with the latest nightly 8 when installing either the ipa or deb. I'll have another iOS 14 device to test with later this week and will report back!

**Comment by badger200** [comment]
iOS 14.4 unc0ver 8.0.2. Same problem (blank screen.) 2nd launch after force close, still blank.

**Comment by UInt2048** [comment]
Please confirm the issue is solved.

**Comment by deepfriedfilth** [comment]
Can confirm. Sites are loading as intended with latest nightly 9 release

**Comment by badger200** [comment]
Default WebKit.org homepage now loads on iOS 14.4 with nightly beta 0.9. But no other websites will load, just stall forever. Tried www. And https etc and nothing works. New tab didn't load either.

**Comment by UInt2048** [comment]
@badger200 Would you mind installing the TrollStore release and testing it with your device jailed?

**Comment by badger200** [comment]
@UInt2048 Actually that's what I was using (jailed, TrollStore). I just tried it jailbroken and it loads other pages now. Complex pages are so slow it's unusable though.

**Comment by bizbuzzone** [comment]
## Source Code Audit Results — SDK Version Gating in v622

### Summary
| Gating Mechanism | Count | Impact |
|-----------------|-------|--------|
| linkedOnOrAfterSDKWithBehavior | 123 calls in 70 files | Runtime behavior changes |
| __IPHONE_OS_VERSION_MIN_REQUIRED | 197 occurrences in 31 files | Compile-time feature disabling |
| @available (Swift) | 4 occurrences | Minimal (UI overlays) |
| os_feature_enabled | 10 occurrences in 5 files | Runtime Apple feature flags |
| API_AVAILABLE declarations | 1,882 occurrences | API availability markers |

### iOS 17.0+ SDK Behaviors (disabled on iOS 16)
6 behaviors disabled when running on iOS 16:
1. FullySuspendsBackgroundContent
2. RunningBoardThrottling
3. **PopoverAttributeEnabled** ← fingerprint-relevant
4. DoesNotOverrideUAFromNSUserDefault
5. EvaluateJavaScriptWithoutTransientActivation
6. ResettingTransitionCancelsRunningTransitionQuirk

### iOS 18.0+ SDK Behaviors (disabled on iOS 16)
9 behaviors disabled:
1. FullySuspendsBackgroundContentImmediately
2. ApplicationStateTrackerDoesNotObserveWindow
3. ThrowOnKVCInstanceVariableAccess
4. **BlockOptionallyBlockableMixedContent** ← security behavior change
5. **LaxCookieSameSiteAttribute** ← networking behavior change
6. **UseCFNetworkNetworkLoader** ← networking implementation
7. BlocksConnectionsToAddressWithOnlyZeros
8. **BlockCrossOriginRedirectDownloads** ← security behavior
9. SupportGameControllerEventInteractionAPI

### HAVE_ Macros Gated by iOS 17+/18+ (PlatformHave.h)
66 occurrences in PlatformHave.h alone, including:
- HAVE_INLINE_PREDICTIONS (iOS 17+)
- HAVE_REDESIGNED_TEXT_CURSOR (iOS 17+)
- HAVE_AVASSETWRITER_WITH_OPUS_SUPPORTED (iOS 17+)
- HAVE_WEB_AUTHN_PRF_API (iOS 18+)
- HAVE_UI_CONVERSATION_CONTEXT (iOS 18.4+)

### Key Fingerprint-Relevant Finding
**PopoverAttributeEnabled** is gated by `linkedOnOrAfterSDKWithBehavior(SDKAlignedBehavior::PopoverAttributeEnabled)` — this means the Popover API (showPopover/hidePopover/togglePopover) may be disabled on CK26 even though the code is compiled in. Need to verify on device.

### Possible Bypass Strategies
1. Hook `_dyld_get_sdk_version()` to return iOS 18 SDK version
2. Hook the `linkedOnOrAfterSDKWithBehavior()` function directly to return true for all behaviors
3. Rebuild WebKit with `-DIOS_SDK_VERSION=180000` or equivalent
4. Individual feature enablement via WKPreferences where possible
