### ISSUE TITLE
Crash ios 14.0.1

### ISSUE THREAD

**Issue by quanghuy2203** [UInt2048/CyberKit#23]
Which version of iOS 14.0.1 can be used? please let me know. Thanks

**Comment by UInt2048** [comment]
Presumably this confirms #22 affected 14.0.1 as well. You should use v0.0.8 nightly 9 (or any future newer release).

**Comment by UInt2048** [comment]
@quanghuy2203

P.S. If it still crashes in v0.0.8 nightly 9, please let me know, because that means I didn't do the fix properly.

**Comment by quanghuy2203** [comment]
I use the mini14 version of TrollStore and it crashes
Video: https://streamable.com/2bfzis

Vào Th 6, 15 thg 12, 2023 lúc 21:00 UInt2048 ***@***.***> đã
viết:

**Comment by bizbuzzone** [comment]
## Removed Features — Source Code Verification Complete

All 10 removed features verified as correctly absent in v622 source (safari-7622-cyberkit-phase2 branch):

| Feature | IDL Status | Verdict |
|---------|-----------|---------|
| window.applicationCache | Not in DOMWindow.idl | ✅ Removed |
| KeyboardEvent.altGraphKey | Not in KeyboardEvent.idl | ✅ Removed |
| KeyboardEvent.keyLocation | Not in KeyboardEvent.idl | ✅ Removed |
| SVGAnimateColorElement | Only in .order file (linker) | ✅ Removed |
| SVGDocument | No .idl file exists | ✅ Removed |
| CSSUnknownRule | Not in any CSS .idl | ✅ Removed |
| webKitBackingStorePixelRatio | Not in CanvasRenderingContext2D.idl | ✅ Removed |
| webkitImageSmoothingEnabled | Not in CanvasRenderingContext2D.idl | ✅ Removed |
| setAlpha() | Not in CanvasRenderingContext2D.idl | ✅ Removed |
| setCompositeOperation() | Not in CanvasRenderingContext2D.idl | ✅ Removed |

**Still need on-device verification** to confirm these are actually undefined at runtime (not just missing from IDL but potentially still compiled via fallback paths).

**Comment by bizbuzzone** [comment]
## Test Page Created

**File**: \`tools/api_audit.html\` — comprehensive Safari 18.x feature verification page

Includes 35 Safari 18.x JS API tests:
- URL.parse, Float16Array, Uint8Array base64/hex methods
- Promise.try, RegExp.escape, Iterator.from + 10 prototype helpers
- Error.isError, Atomics.pause, document.startViewTransition
- document.fragmentDirective, getHTML, Response.bytes
- PointerEvent properties, CookieStore API, Brotli CompressionStream

Plus 10 removed features tests (verified all correctly absent from v622 IDL).

**To test**: Copy to device and open in Safari, or host on local network.

**Comment by nilFinx** [comment]
@bizbuzzone, who are you? You just sent multiple replies across multiple issues - closed one included, like this, and the formatting seems like AI.

**Comment by UInt2048** [comment]
@nilFinx They have been provided an opportunity to respond, and now have been blocked after failing to answer.
