### ISSUE TITLE
Enhancement: Adblock integration

### ISSUE THREAD

**Issue by plia7** [UInt2048/CyberKit#29]
Hello,

I'm using CyberKit alpha 0.0.8-alpha on my iPhone 12 Pro Max on iOS 14.4.1 with Taurine jailbreak.
I also have the MYbloXX tweak version 4.020822-14 installed which has a pop-up blocker for Safari.
Is it possible to use MyBloXX with CyberKit too or is there another existing/planned feature/add-on or tweak to use in CyberKit?

**Steps to reproduce:** Click on a link to start a video stream, this will cause a popup ad website to show.

**Expected behavior:** Be presented with similar choices as MYBloXX gives in Safari to decide if you want to allow or block the popup website.

**Actual behavior:** CyberKit opens the popup ad website.

Thank you.

**Comment by UInt2048** [comment]
Does this same behavior occur in other third-party browsers, such as if you download Firefox from the App Store?

**Comment by plia7** [comment]
> Does this same behavior occur in other third-party browsers, such as if you download Firefox from the App Store?

@UInt2048 There are several third-party iOS browsers such as Opera Touch, Brave and Microsoft Edge that come with a built in ad block feature.

Some requested it for Firefox iOS: 

https://github.com/mozilla-mobile/firefox-ios/issues/5198

https://github.com/mozilla-mobile/firefox-ios/issues/7374

But so far from my understanding, they only provide basic no tracking protection so it's quite limited.
Would be nice to have something similar to those that have it as built in or something similar to what MyBloXX does for Safari.

Thanks.

**Comment by UInt2048** [comment]
This issue will consider a functional Brave build modified to use CyberKit to be a resolution.

**Comment by plia7** [comment]
> This issue will consider a functional Brave build modified to use CyberKit to be a resolution.

@UInt2048 Not sure what it means but if I try to go the app store now to download Brave it says: "Requires iOS 15.0 or later.". 

Actually I was able to use AppStore++ to download and run the latest compatible version for my iOS: Brave Version 1.48.1.

So hopefully what you suggest will still work on my iOS 14.4.1.

Thanks.

**Comment by plia7** [comment]
@UInt2048 I see in settings a setting called: Block Pop-up Windows which is turned on.

I tried to test it in some test popup browser website:

https://www.webroot.com/services/popuptester1.htm

But it's hard to test with the slow loading issue, so this might need to be revisited after the loading stuck issue is fixed.

Thanks.

**Comment by UInt2048** [comment]
This issue is now closed due to the release of https://github.com/UInt2048/CyberKit/releases/tag/v0.0.9-nightly.01.

**Comment by plia7** [comment]
> This issue is now closed due to the release of https://github.com/UInt2048/CyberKit/releases/tag/v0.0.9-nightly-01.

Is that version available for iOS 14? Did you add ad block integration in that version?

**Comment by UInt2048** [comment]
> Is that version available for iOS 14?

No. However, a sequence of commits like this reference implementation will be the base of all future CyberKit releases. iOS 14 support will be re-implemented in this branch, don't worry.

> Did you add ad block integration in that version?

No, and now I don't ever have to, because you can find a browser compatible with iOS 14 that has the integration you're looking for. It doesn't even have to be open source any more, an IPA will do.

In this release, for the first time, the exact same fakesign script without any modifications is used to create both MobileMiniBrowser and Fennec releases. It's not actually limited to these either — you should be able to use it with virtually any browser that depends on the system WebKit frameworks.

**Comment by plia7** [comment]
> > Is that version available for iOS 14?
> 
> 
> 
> No. However, a sequence of commits like this reference implementation will be the base of all future CyberKit releases. iOS 14 support will be re-implemented in this branch, don't worry.
> 
> 
> 
> > Did you add ad block integration in that version?
> 
> 
> 
> No, and now I don't ever have to, because you can find a browser compatible with iOS 14 that has the integration you're looking for. It doesn't even have to be open source any more, an IPA will do.
> 
> 
> 
> In this release, for the first time, the exact same fakesign script without any modifications is used to create both MobileMiniBrowser and Fennec releases. It's not actually limited to these either — you should be able to use it with virtually any browser that depends on the system WebKit frameworks.

I'm using CyberKit alpha 0.0.8-alpha and MiniBrowser 0.0.9 alpha nightly 9  for iOS 14 - Do I just wait now for the new release to be able to use other browsers with CyberKit?

Thanks.
