### ISSUE TITLE
MobileMiniBrowser won't load any sites except the default WebKit url

### ISSUE THREAD

**Issue by SKDemon820** [UInt2048/CyberKit#42]
The Fennec version loads sites fine, but the mobileminibrowser won't load any searched sites, as seen in the video.  I did configure the Jetsam as needed

iOS: 14.2
Cyberkit: 0.0.8-a (iOS 14)

https://github.com/UInt2048/CyberKit/assets/62918850/996874e5-b6c2-4a75-8426-22b0bdced185

**Comment by plia7** [comment]
@UInt2048 I believe this issue is a duplicate and the same issue as that I already reported here:

https://github.com/UInt2048/CyberKit/issues/39

@SKDemon820 The workaround for it for now: You have to type "www.google.com" (without quotes) for it to work.

Thanks.

**Comment by UInt2048** [comment]
Agreed, closing as duplicate of #39
