### ISSUE TITLE
Compile Fennec from source for rootless devices

### ISSUE THREAD

**Issue by Soneoylys** [UInt2048/CyberKit#46]
Hi, I found the iOS 14 MobileMiniBrowser release of 0.0.9 alpha works on rootless iOS 15 devices.

I wanna give Fennec a shot. Which branch should I use?

**Comment by UInt2048** [comment]
You should use the current development branch, `safari-7619.1.26.31-branch`.

https://github.com/UInt2048/CyberKit/releases/tag/v0.0.9-nightly.01 has compiled Fennec releases for iOS 16. iOS 15 support will be added shortly.

**Comment by Midnight145** [comment]
Curious, any news on iOS 15 releases? I currently don't have a Mac to build from source myself.

Thank you!
