### ISSUE TITLE
404 error when installing "CyberKit MobileMiniBrowser (iOS 15 Rootless)"

### ISSUE THREAD

**Issue by DetachHead** [UInt2048/CyberKit#6]
the other packages seem to install fine

![image](https://github.com/UInt2048/CyberKit/assets/57028336/9c675cca-8fb2-4313-8ab8-e9548624af73)

**Comment by UInt2048** [comment]
Please sign into GitHub in Safari on the device. The issue occurs because GitHub Releases is used to host the DEB files on my repo (except for the dummy packages)

**Comment by DetachHead** [comment]
@UInt2048 i am logged into github. since it's a public repo you shouldn't have to log in though, but i don't think that's the issue. the URLs here seem to be incorrect https://github.com/UInt2048/uint2048.github.io/blob/master/Packages#L345

i've made a PR with what i believe to be the correct URLs: https://github.com/UInt2048/uint2048.github.io/pull/1
