### ISSUE TITLE
CyberKit Fennec v0.0.7 alpha crashes

### ISSUE THREAD

**Issue by shivsey** [UInt2048/CyberKit#8]
Followed Jetsam IOS 14 instructions, used script (replacing J307 with J418) on OSX to modify plist then double checked by viewing plist file after replacing original.  Rebooted and rejailbreaked.

MiniBrowser launches and runs, but com.matthewbenedict.ios.fennec+14_0.0.7-alpha_iphoneos-arm.deb and  com.matthewbenedict.ios.fennec14_0.0.7-alpha_all.ipa both crash on launch.  I was able to run Client.ipa and com.matthewbenedict.ios.fennec_0.0.6-alpha_all.deb, although crashes when I try to sync to my firefox profile.

<details>
<summary>Cr4shed log</summary>

Date: 7/3/23, 8:26 PM
Process: Client
Bundle id: com.matthewbenedict.ios.Fennec
Device: iPad Pro (11-inch) (2nd generation), iOS 14.3
Bundle version: 115.0

Exception type: EXC_SOFTWARE (SIGABRT)
Exception subtype: EXC_UNIX_ABORT
Exception codes: 0x0000000000010002, 0x0000000000000000
Culprit: Unknown
Termination Reason: dyld: Using shared cache: AE74B079-BF6C-377C-9F59-C4F97F338C4E
Library not loaded: @rpath/Common_17A2E8D93C1D2F_PackageProduct.framework/Common_17A2E8D93C1D2F_PackageProduct
 Referenced from: /Applications/Client.app/Client
 Reason: image not found

Triggered by thread: 0
Thread name: 
Call stack:
0  dyld                          0x000000010802f440 0x107fd8000 + 357440    // __abort_with_payload
1  dyld                          0x00000001080376e0 0x107fd8000 + 390880    // abort_with_payload_wrapper_internal
2  dyld                          0x0000000108037714 0x107fd8000 + 390932    // __unw_set_reg.cold.1
3  dyld                          0x0000000107fdd05c 0x107fd8000 + 20572      // dyld::fastBindLazySymbol(ImageLoader**, unsigned long)
4  dyld                          0x0000000107fe00b8 0x107fd8000 + 32952      // dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*)
5  dyld                          0x0000000107fd9258 0x107fd8000 + 4696      // dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*)
6  dyld                          0x0000000107fd9038 0x107fd8000 + 4152      // _dyld_start

Register values:
PC: 0x16b326220        LR: 0x16b326260        CPSR: 0x802f440
x0: 0x4400000006        x1: 0x6                x2: 0x1
x3: 0x16b326690        x4: 0x8f                x5: 0x16b326290
x6: 0x0                x7: 0x746e65696c432f    x8: 0x0
x9: 0x20                x10: 0x9                x11: 0x1
x12: 0xb0              x13: 0x79              x14: 0xbf
x15: 0x6c              x16: 0x37              x17: 0x209
x18: 0x1080297b4        x19: 0x0                x20: 0x0
x21: 0x16b326290        x22: 0x8f              x23: 0x16b326690
x24: 0x1                x25: 0x6                x26: 0x16b3273a8
x27: 0x108050000        x28: 0x108050000

Loaded images:
0: /Applications/Client.app/Client
1: /usr/lib/dyld
2: /Applications/Client.app/Frameworks/CyberScriptCore.framework/CyberScriptCore
3: /usr/lib/libc++.1.dylib
4: /usr/lib/libxml2.2.dylib
5: /usr/lib/libz.1.dylib

{"ProcessBundleID":"com.matthewbenedict.ios.Fennec","ProcessName":"Client","Culprit":"Unknown"}

</details>

**Comment by UInt2048** [comment]
Thanks for the report. It looks like I screwed up and some of the frameworks it needs are not present.

**Comment by shivsey** [comment]
Well you clearly stated it as an Alpha release so completely
understandable.  Just starting to find more and more sites not loading that
I believe is tied to the outdated webkit I have on 14.3.  It would be nice
to test some of them on your version.

**Comment by UInt2048** [comment]
@shivsey Please use MobileMiniBrowser for now until I have time to take care of it. Thanks for the report.

**Comment by UInt2048** [comment]
The builds erroneously missing frameworks have been republished. Feel free to reinstall v0.0.7 alpha now.
