### ISSUE TITLE
[14.4] cannot install via TrollStore

### ISSUE THREAD

**Issue by HackZy01** [UInt2048/CyberKit#9]
com.matthewbenedict.ios.fennec14_0.0.7-alpha_all.ipa

![IMG_7073](https://github.com/UInt2048/CyberKit/assets/77678316/84a2ea0a-6ad1-42df-932c-c2c26818e555)

**Comment by UInt2048** [comment]
@HackZy01 You need to uninstall the DEB first.

#8 is still a problem though.
